# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
  # python3-sphinxcontrib.plantuml installs an old version of plantuml ...
  # But is needed, to install dependencies ..
  # Below, an other plantUML jar is installed
  # (Both are needed ... it also in the requerments-file, but needed here)
    - python3-sphinxcontrib.plantuml
  jobs:
    post_install:
      # Install a  newer version op plantuml -- keep in sync witch 'conf.py'!
      - mkdir -p ${READTHEDOCS_VIRTUALENV_PATH}/libexec
      - curl  -o ${READTHEDOCS_VIRTUALENV_PATH}/libexec/plantuml.jar  -L https://github.com/plantuml/plantuml/releases/download/v1.2024.4/plantuml-1.2024.4.jar

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: requirements.txt