/' (C) ALbert Mietus, 2020; dropjes licencie: Use at will, and give me liquorice to say thanks.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''/

@startuml
!include SwBMnl-skin.iuml

partition "BDD & TDD" #EEEEFF/DDDDFF {
(*)             --> [e,g. //UserStories//] "Specifications"         as SPECS

SPECS           --> [BDD] ===BDD===
===BDD===       --> "SystemTest\nDesign"                            as STD
===BDD===       --> "Architecture &\n Design"                       as AenD
STD             ..> AenD

STD             -[#808080,dotted]-> [<color:white><back:#808080>auto] "Exec SysTests\n (all, continuesly)"     as STE
If "OK" then
                --> [DONE] (*)
Else
                -up[#ForestGreen,dashed]-> [<color:ForestGreen><b>repeat] SPECS

partition Design #DDDDFF-CCCCFF {

AenD            --> [TDD.m] ===TDDm===
===TDDm===      --> "ModuleTests\nDesign"                           as MTD
===TDDm===      --> "Module & Unit\nDesign"                         as MUD
MTD             ..> MUD

MTD             -[#808080,dotted]-> [<color:white><back:#808080>auto]  "Exec Module Tests\n (all, continuesly)"  as MTE
If "OK" then
                --> STE
else
                -up[#ForestGreen,dashed]-> [<color:ForestGreen><b>repeat] MTD

partition Coding #CCCCFF|BBBBFF {

MUD             --> [TDD.u] ===TDDu===
===TDDu===      --> "UnitTest\nDesign"                              as UTD
===TDDu===      --> "Coding"                                        as CODE
UTD             ..> CODE

UTD             -[#808080,dotted]--> [<color:white><back:#808080>auto] "Exec UnitTests\n(all, continuesly)"     as UTE
If "OK" then
                --> MTE

Else
                -up[#ForestGreen]->		[<color:ForestGreen><b>improve] CODE
                -up[#ForestGreen,dashed]-> 	[<color:ForestGreen><b>tweek] UTD


CODE -> UTE
}
}
}
@enduml
